export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const UPDATE_ADDRESS_FIELD = 'UPDATE_ADDRESS_FIELD';
export const UPDATE_ALL_DATES = 'UPDATE_ALL_DATES';
export const UPDATE_DATE = 'UPDATE_DATE';
